### PR TITLE
Added new example

### PR DESCRIPTION
**Pull request by besnoi**
Didnt add screenshot for the creator's OS is different from mine

### CODE REVIEW

**Review by Moosems — CHANGES_REQUESTED** [review]
Change comment to reflect that this is a stopwatch, not a calculator
What it should be:
```python
'''Simple Stopwatch with Sun Valley Theme'''

from tkinter import Tk
from tkinter.ttk import Button, Label
from datetime import datetime
import sv_ttk
```

**Comment by Moosems** [comment]
@rdbende has previously said that he is not a fan of star imports which is why i requested such changes. As for the Labels and Buttons if you are trying to show the prowess of `sv_ttk` then at least use it's own widgets

**Comment by rdbende** [comment]
@besnoi thanks for this example! ❤️ I'll clean it up a bit to be more consistent with the other examples, but this is looking promising!

@Moosems `sv_ttk` doesn't have its own widgets, it has only utility functions to set the SV theme for `tkinter.ttk` widgets

**Comment by Moosems** [comment]
@rdbende @besnoi My bad. I was under the impression for some reason that sv_ttk imported the widgets itself. I'm sorry if I came across rude there. I'm very sorry

**Comment by rdbende** [comment]
@Moosems no problem ;)

**Pull request closed without merging**
